### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by MrJosu** [Dhovin/pihole-unbound#1]
Hello, your repo don't exist to install on Unraid :) Wanted to try some easy pihole install :D

**Comment by Dhovin** [comment]
I didn't realize till this past saturday that it wasn't showing up. Squid added me recently. Not sure when it will fully propigate out.

**Comment by Dhovin** [comment]
OHHH! I see now. I renamed the repo and didn't update the template. my bad!

**Comment by Dhovin** [comment]
wow, docker.com repo is missing too! I really bungled this one.

**Comment by MrJosu** [comment]
lol thank you for quick response :)

**Comment by Dhovin** [comment]
Unfortunatly, I'm gonna have to remove this for now. It is going to take a bit of fixing. sorry for the trouble.The script works for a direct install in Ubuntu 20.4.5 LTS but needs a lot of tweaking for a docker. It might be some time before I get it working. There are several PiHole dockers in the app store that work great.

**Comment by MrJosu** [comment]
Would be amazing if you can add wireguard for this combo, there is one repo on GitHub but unbound not working
